name: Run YOLO Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download YOLO model from Google Drive
        run: |
          mkdir -p weights
          gdown --id 11-HcwFwueby8S_QjaFEUucUw9odDrQpn -O weights/best.pt

      - name: Run YOLO script
        run: |
          python run_yolo.py --weights weights/best.pt
